version: '3'

services:

  my_mongo_db:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./bd/mongodb:/data/db

  mymysql:
    image: mysql:8.0.33
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD= root
    volumes:
      - ./bd/mysql:/var/lib/mysql

  mymariadb:
    image: mariadb:10.6.14
    ports:
      - 3307:3306
    environment:
      - MARIADB_ROOT_PASSWORD= root
    volumes:
      - ./bd/mariadb:/var/lib/mysql

  my_express:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:4000
    environment:
      - MONGO_DB_HOST= my_mongo_db

      - MYSQL_HOST= mymysql
      - MYSQL_USER= root
      - MYSQL_PASSWORD= root

      
    
  